apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: prometheus-adapter
  name: prometheus-adapter-server-resources
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: 
    - get
    - list
    - watch
    - create
    - update
    - delete
