apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.10.0
    app: prometheus-adapter
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: 'prometheus-adapter-serving-cert'
    service.alpha.openshift.io/serving-cert-secret-name: 'prometheus-adapter-serving-cert'
  name: custom-metrics-prometheus-adapter
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
