kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-adapter-prometheus-config
  labels:
    app: prometheus-adapter
data:
  prometheus-config.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/ssl/certs/service-ca.crt
        server: prometheus-url-placeholder
      name: prometheus-k8s
    contexts:
    - context:
        cluster: prometheus-k8s
        user: prometheus-k8s
      name: prometheus-k8s
    current-context: prometheus-k8s
    kind: Config
    preferences: {}
    users:
    - name: prometheus-k8s
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
